// This file was auto-generated by prisma-generator-typescript-interfaces

export type ReactionTypeEnum = "UPVOTE" | "DOWNVOTE";

export type EntityTypeEnum = "POST" | "COMMENT" | "REPLY";

export type PurchaseStatusEnum = "AVAILABLE" | "SOLD";

export interface IBookEntity {
	id: string;
	title: string;
	author: string;
	publisher?: string | null;
	publishYear?: string | null;
	isbn?: string | null;
	language?: string | null;
	buyPrice: number;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	predictionResult?: IPredictionResultEntity | null;
	post?: IPostEntity | null;
}

export interface IPredictionResultEntity {
	id: string;
	percentage: number;
	wornOutRatio: number;
	rippedRatio: number;
	overallRatio: number;
	buyPrice: number;
	recommendPrice: number;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	bookId?: string | null;
	book?: IBookEntity | null;
}

export interface IPostEntity {
	id: string;
	image: string;
	content: string;
	price: number;
	status: PurchaseStatusEnum;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	bookId?: string | null;
	userId?: string | null;
	book?: IBookEntity | null;
	user?: IUserEntity | null;
	comment?: ICommentEntity[];
	reactions?: IReactionEntity[];
}

export interface ICommentEntity {
	id: string;
	content: string;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	userId?: string | null;
	postId?: string | null;
	user?: IUserEntity | null;
	post?: IPostEntity | null;
	commentReply?: ICommentReplyEntity[];
	reactions?: IReactionEntity[];
}

export interface ICommentReplyEntity {
	id: string;
	content: string;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	userId?: string | null;
	commentId?: string | null;
	comment?: ICommentEntity | null;
	user?: IUserEntity | null;
	reactions?: IReactionEntity[];
}

export interface IReactionEntity {
	id: string;
	userId: string;
	entityType: EntityTypeEnum;
	reaction: ReactionTypeEnum;
	commentReplyId?: string | null;
	commentId?: string | null;
	postId?: string | null;
	commentReply?: ICommentReplyEntity | null;
	comment?: ICommentEntity | null;
	post?: IPostEntity | null;
	user?: IUserEntity;
}

export interface IAccountEntity {
	id: string;
	email: string;
	password?: string | null;
	googleTokenId?: string | null;
	refreshToken?: string | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	user?: IUserEntity | null;
}

export interface IProfileEntity {
	id: string;
	name: string;
	image?: string | null;
	bio?: string | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	user?: IUserEntity | null;
}

export interface IUserEntity {
	id: string;
	username: string;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	accountId?: string | null;
	profileId?: string | null;
	account?: IAccountEntity | null;
	profile?: IProfileEntity | null;
	geolocation?: IGeolocationEntity | null;
	post?: IPostEntity[];
	comment?: ICommentEntity[];
	commentReply?: ICommentReplyEntity[];
	reactions?: IReactionEntity[];
}

export interface IGeolocationEntity {
	id: string;
	latitude?: number | null;
	longitude?: number | null;
	city?: string | null;
	createdAt?: Date | null;
	updatedAt?: Date | null;
	userId?: string | null;
	user?: IUserEntity | null;
}
